GCSOFT.MVC/GCSOFT.MVC.AGENCY/Areas/Agency/Controllers/CustomerAgencyBuySummaryController.cs
using AutoMapper;
using GCSOFT.MVC.AGENCY.Areas.Administrator.Controllers;
using GCSOFT.MVC.AGENCY.Areas.Agency.Data;
using GCSOFT.MVC.AGENCY.Areas.Transaction.Data;
using GCSOFT.MVC.AGENCY.Helper;
using GCSOFT.MVC.Data.Common;
using GCSOFT.MVC.Model.AgencyModel;
using GCSOFT.MVC.Model.MasterData;
using GCSOFT.MVC.Model.StoreProcedue;
using GCSOFT.MVC.Service.AgencyService.Interface;
using GCSOFT.MVC.Service.ExeclOfficeEngine;
using GCSOFT.MVC.Service.MasterDataService.Interface;
using GCSOFT.MVC.Service.StoreProcedure.Interface;
using GCSOFT.MVC.Service.SystemService.Interface;
using GCSOFT.MVC.Web.Helper;
using GCSOFT.MVC.Web.Helper.ActionFilters;
using GCSOFT.MVC.Web.ViewModels;
using GCSOFT.MVC.Web.ViewModels.MasterData;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace GCSOFT.MVC.AGENCY.Areas.Agency.Controllers
{
    [CompressResponseAttribute]
    public class CustomerAgencyBuySummaryController : BaseController
    {
        #region -- Properties --
        private readonly IVuViecService _vuViecService;
        private readonly IStoreProcedureService _storeService;
        private readonly ICardLineService _cardLineService;
        private readonly ICardEntryService _cardEntryService;
        private readonly IAgencyCardService _agencyAndCardService;
        private readonly IOptionLineService _optionLineService;
        private readonly IAgencyService _agencyService;
        private readonly IHistoryRecall _historyRecall;
        private string sysCategory = "AGENCYCUSTBUYTOTAL";
        private bool? permission = false;
        private string hasValue;
        #endregion

        #region -- Contructor --
        public CustomerAgencyBuySummaryController
            (
                IVuViecService vuViecService
                , IStoreProcedureService storeService
                , ICardLineService cardLineService
                , ICardEntryService cardEntryService
                , IAgencyCardService agencyAndCardService
                , IOptionLineService optionLineService
                , IAgencyService agencyService
                , IHistoryRecall historyRecall
            ) : base(vuViecService)
        {
            _vuViecService = vuViecService;
            _storeService = storeService;
            _cardLineService = cardLineService;
            _cardEntryService = cardEntryService;
            _agencyAndCardService = agencyAndCardService;
            _optionLineService = optionLineService;
            _agencyService = agencyService;
            _historyRecall = historyRecall;
        }
        #endregion
        public ActionResult Index(CustomerAgencyBuySummaryPage c)
        {
            #region -- Role user --
            permission = GetPermission(sysCategory, Authorities.View);
            if (!permission.HasValue) return RedirectToAction("Index", "Login", new { area = "administrator", url = CurrentUrl() });
            if (!permission.Value) return View("AccessDenied");
            #endregion
            var userInfo = GetUser();
            c.AgencyId = c.AgencyId ?? userInfo.agencyInfo.Id;
            var cardHistory = c;

            var fromDate = new DateTime();
            var toDate = new DateTime();
            if (string.IsNullOrEmpty(c.fd))
            {
                fromDate = new DateTime(DateTime.Now.Year, DateTime.Now.Month, 1);
                toDate = fromDate.AddMonths(1).AddDays(-1);
                cardHistory.CustAgencySumList = new List<SpCustomerAgencyBuySumary>();
            }
            else
            {
                fromDate = DateTime.Parse(StringUtil.ConvertStringToDate(c.fd));
                toDate = DateTime.Parse(StringUtil.ConvertStringToDate(c.td));

                cardHistory.CustAgencySumList = _storeService.sp_CustomerAgencyBuySumary(c.AgencyId ?? 0, c.SeriNumber ?? "", c.FullName ?? "", c.PhoneNo ?? "", c.Email ?? "", c.LevelCode ?? "", fromDate, toDate);
            }
            cardHistory.FromDate = fromDate;
            cardHistory.ToDate = toDate;
            cardHistory.LevelList = Mapper.Map<IEnumerable<VM_OptionLine>>(_optionLineService.FindAll("LV")).ToSelectListItems(c.LevelCode ?? "");
            cardHistory.AgencyDDL = _storeService.AgencyParentFindAll("FINDALL", GetUser().agencyInfo.Id).ToSelectListItems(c.AgencyId ?? 0);
            return View(cardHistory);
        }
        public ActionResult Download(CustomerAgencyBuySummaryPage c)
        {
            var userInfo = GetUser();
            c.AgencyId = c.AgencyId ?? userInfo.agencyInfo.Id;
            var cardHistory = c;
            var fromDate = new DateTime();
            var toDate = new DateTime();
            if (string.IsNullOrEmpty(c.fd))
            {
                fromDate = new DateTime(DateTime.Now.Year, DateTime.Now.Month, 1);
                toDate = fromDate.AddMonths(1).AddDays(-1);
                cardHistory.CustAgencySumList = new List<SpCustomerAgencyBuySumary>();
            }
            else
            {
                fromDate = DateTime.Parse(StringUtil.ConvertStringToDate(c.fd));
                toDate = DateTime.Parse(StringUtil.ConvertStringToDate(c.td));

                cardHistory.CustAgencySumList = _storeService.sp_CustomerAgencyBuySumary(c.AgencyId ?? 0, c.SeriNumber ?? "", c.FullName ?? "", c.PhoneNo ?? "", c.Email ?? "", c.LevelCode ?? "", fromDate, toDate);
            }
            var agencyInfo = Mapper.Map<AgencyCard>(_agencyService.GetBy2(c.AgencyId ?? 0));
            var res = cardHistory.CustAgencySumList;
            var dataModel = res.ToList().ConvertToDataTable();
            dataModel.TableName = "Model";

            List<KeyValuePair<string, object>> excelItems = new List<KeyValuePair<string, object>>();
            excelItems.Add(new KeyValuePair<string, object>("AgencyName", string.Format("{0} {1}", agencyInfo.AgencyType == AgencyType.Staff ? "Nhân Viên " : "Bưu điện ", string.IsNullOrEmpty(agencyInfo.CompanyName) ? agencyInfo.FullName : agencyInfo.CompanyName)));
            excelItems.Add(new KeyValuePair<string, object>("MonthYear", string.Format("BIÊN BẢN ĐỐI SOÁT THÁNG {0}/{1}", fromDate.Month, fromDate.Year)));
            excelItems.Add(new KeyValuePair<string, object>("FromToDate", string.Format("Từ ngày {0} đến ngày {1}", c.fd, c.td)));
            Excel.ExcelItems = excelItems;

            var stream = Excel.ExportReport(dataModel, HttpContext.Server.MapPath("/Areas/Agency/Report/BaoCaoDoiSoat02.xlsx"), false, OfficeType.XLSX);
            return File(stream, OfficeContentType.XLSX, "BaoCaoDoiSoat.xlsx");
        }
        public Dictionary<string, string> CboStatus()
        {
            Dictionary<string, string> dics = new Dictionary<string, string>();
            dics["BUY"] = "Ngày Bán";
            dics["ACTIVE"] = "Ngày Khách Kích Hoạt";
            return dics;
        }
    }
}

GCSOFT.MVC/GCSOFT.MVC.AGENCY/Areas/Agency/Views/CustomerAgencyBuySummary/Index.cshtml
@model GCSOFT.MVC.AGENCY.Areas.Agency.Data.CustomerAgencyBuySummaryPage
@{
    ViewBag.Title = "Đối Soát";
}
<div id="page_content_inner">
    <div class="md-card">
        <div class="md-card-toolbar">
            <h3 class="md-card-toolbar-heading-text">
                Tìm kiếm
            </h3>
        </div>
        <div class="md-card-content">
            <div class="uk-grid" data-uk-grid-margin>
                <div class="uk-width-medium-1-1">
                    <div class="parsley-row">
                        <label for="Type">Danh Sách Đại Lý</label>
                        @Html.DropDownListFor(model => model.AgencyId, Model.AgencyDDL, "[ Chọn tất cả ]", new { @class = "md-input label-fixed" })
                    </div>
                </div>
            </div>
            <div class="uk-grid" data-uk-grid-margin>
                <div class="uk-width-medium-1-3">
                    <label for="Type">Từ Ngày</label>
                    @Html.TextBoxFor(model => model.FromDateStr
                                         , new Dictionary<string, Object> {
                                                { "class", "md-input label-fixed validate[required,funcCall[DateFormat[]]" }
                                                , { "autocomplete", "off" }
                                                , { "placeholder", "dd/MM/yyyy" }
                                                , { "data-uk-datepicker", "{format:'DD/MM/YYYY'}" }
                                         })
                </div>
                <div class="uk-width-medium-1-3">
                    <label for="Type">Đến Ngày</label>
                    @Html.TextBoxFor(model => model.ToDateStr
                                         , new Dictionary<string, Object> {
                                                { "class", "md-input label-fixed validate[required,funcCall[DateFormat[]]" }
                                                , { "autocomplete", "off" }
                                                , { "placeholder", "dd/MM/yyyy" }
                                                , { "data-uk-datepicker", "{format:'DD/MM/YYYY'}" }
                                         })
                </div>
                <div class="uk-width-medium-1-3">
                    <div class="parsley-row">
                        <label for="Type">Loại Thẻ</label>
                        @Html.DropDownListFor(model => model.LevelCode, Model.LevelList, "[ Chọn ]", new { @class = "md-input label-fixed" })
                    </div>
                </div>
            </div>
            <div class="uk-grid" data-uk-grid-margin>
                <div class="uk-width-medium-1-4">
                    <label for="Type">Họ Và Tên Phụ Huynh</label>
                    @Html.TextBoxFor(model => model.FullName, new { @class = "md-input label-fixed" })
                </div>
                <div class="uk-width-medium-1-4">
                    <label for="Type">Số Điện Thoại</label>
                    @Html.TextBoxFor(model => model.PhoneNo, new { @class = "md-input label-fixed" })
                </div>
                <div class="uk-width-medium-1-4">
                    <label for="Type">Email</label>
                    @Html.TextBoxFor(model => model.Email, new { @class = "md-input label-fixed" })
                </div>
                <div class="uk-width-medium-1-4">
                    <label for="Type">Seri Number</label>
                    @Html.TextBoxFor(model => model.SeriNumber, new { @class = "md-input label-fixed" })
                </div>
            </div>
            <div class="uk-grid" data-uk-grid-margin>
                <div class="uk-width-medium-1-1 uk-text-right">
                    <a id="btnSearch" href="javascript:void(0);" class="md-btn md-btn-primary uk-margin-small-top"><i class="material-icons">&#xE8B6;</i> Tìm Kiếm</a>
                    <a id="btnDowload" href="javascript:void(0);" class="md-btn md-btn-primary uk-margin-small-top"> Download</a>
                </div>
            </div>
        </div>
    </div>
    <div class="md-card">
        <div class="md-card-toolbar">
            <h3 class="md-card-toolbar-heading-text">
                @ViewBag.Title
            </h3>
        </div>
        <div class="md-card-content">
            <div class="uk-overflow-container">
                <table class="uk-table uk-table-nowrap table_check">
                    <thead>
                        <tr>
                            <th class="uk-width-1-10 uk-text-center"><strong>STT</strong></th>
                            <th><strong>Cấp độ</strong></th>
                            <th><strong>Thời gian</strong></th>
                            <th><strong>ĐVT</strong></th>
                            <th><strong>Số lượng</strong></th>
                            <th><strong>Doanh số</strong></th>
                        </tr>
                    </thead>
                    <tbody>
                        @{ int stt = 0; }
                        @foreach (var item in Model.CustAgencySumList)
                        {
                        <tr>
                            <td class="uk-text-center">@(++stt)</td>
                            <td>
                                @item.LevelName
                            </td>
                            <td>
                                @item.DurationName
                            </td>
                            <td>
                                Tài khoản
                            </td>
                            <td class="uk-text-right">
                                @string.Format("{0:#,##0}", item.NoOfSerinumber)
                            </td>
                            <td class="uk-text-right">
                                @string.Format("{0:#,##0}", item.TotalAmount)
                            </td>
                        </tr>
                        }
                    </tbody>
                    <tfoot>
                        <tr>
                            <td class="uk-text-center">&nbsp;</td>
                            <td>
                                &nbsp;
                            </td>
                            <td>
                                &nbsp;
                            </td>
                            <td class="uk-text-bold">
                                Tổng cộng
                            </td>
                            <td class="uk-text-bold uk-text-right">
                                @string.Format("{0:#,##0}", Model.CustAgencySumList.Sum(d => d.NoOfSerinumber))
                            </td>
                            <td class="uk-text-bold uk-text-right">
                                @string.Format("{0:#,##0}", Model.CustAgencySumList.Sum(d => d.TotalAmount))
                            </td>
                        </tr>
                    </tfoot>
                </table>
            </div>
        </div>
    </div>
</div>
<script type="text/javascript" src="@Url.Content("~/Scripts/cms/vendor/paging/pajinatify.js")"></script>
<link type="text/css" href="@Url.Content("~/Scripts/cms/vendor/paging/pajinatify.css")" rel="stylesheet" />
<script type="text/javascript">
    $(document).ready(function () {
        $('#btnSearch').click(function () {
            window.location.href = '@Url.Action("Index", "CustomerAgencyBuySummary", new { area = "Agency" })' + '?p=0' + querySearch();
        });
        $('select').select2({
            selectOnClose: true
        });
        $('#btnDowload').click(function () {
            var url = '@Url.Action("Download", "CustomerAgencyBuySummary", new { area = "Agency" })' + '?p=0' + querySearch();
            $(location).attr('href', url);
        });
    });
    function querySearch() {
        return '&FullName=' + $('#FullName').val() + '&PhoneNo=' + $('#PhoneNo').val() + '&Email=' + $('#Email').val() + '&SeriNumber=' + $('#SeriNumber').val() + '&fd=' + $('#FromDateStr').val() + '&td=' + $('#ToDateStr').val() + '&LevelCode=' + $('#LevelCode option:selected').val() + '&AgencyId=' + $('#AgencyId option:selected').val();
    }
    function DateFormat(field, rules, i, options) {
        var regex = /^(0?[1-9]|[12][0-9]|3[01])[\/\-](0?[1-9]|1[012])[\/\-]\d{4}$/;
        if (!regex.test(field.val())) {
            return "Vui lòng nhập ngày theo định dạng dd/MM/yyyy.";
        }
    }
</script>