GCSOFT.MVC/GCSOFT.MVC.STNHD/Controllers/hientaiController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace GCSOFT.MVC.STNHD.Controllers
{
    public class hientaiController : Controller
    {
        // GET: hientai
        public ActionResult v(int? id)
        {
            var _id = id ?? 10;
            switch (_id)
            {
                case 10:
                    ViewBag.TitleVideo = "Hướng dẫn cài đặt ứng dụng và đăng ký tài khoản Hiền Tài";
                    ViewBag.link = "https://stnhd.com/Files/hientai/setup.mp4";
                    break;
                case 20:
                    ViewBag.TitleVideo = "Hướng dẫn ghi nhận và theo dõi quá trình rèn luyện Hiền Tài";
                    ViewBag.link = "https://stnhd.com/Files/hientai/theodoi.mp4";
                    break;
            }
            return View();
        }
        public ActionResult tl()
        {
            return View();
        }
        public ActionResult tud()
        {
            return View();
        }
    }
}

GCSOFT.MVC/GCSOFT.MVC.STNHD/Views/hientai/tl.cshtml
@{
    ViewBag.Title = "Tài Liệu Hướng Dẫn";
    Layout = "~/Views/Shared/_LayoutOC.cshtml";
}
<link href="@Url.Content("~/Content/Videos.css")" rel="stylesheet" />
<div class="container">
    @*<div class="jumbotron">
        <div class="txt divcenter">
            <h2>@ViewBag.Title</h2>
        </div>
    </div>*@
    <div class="row">
        <h3 style="text-align: center; font-weight: bold; color: #FF660F; font-family: Merriweather;">@ViewBag.Title</h3>
        <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
            <iframe style="width:100%;height:800px" src="https://online.fliphtml5.com/kksyd/jyye/" seamless="seamless" scrolling="no" frameborder="0" allowtransparency="true" allowfullscreen="true"></iframe>

        </div>
    </div>
</div>

GCSOFT.MVC/GCSOFT.MVC.STNHD/Views/hientai/tud.cshtml
@{
    ViewBag.Title = "Ứng Dụng Tâm Trí Lực";
    Layout = "~/Views/Shared/_LayoutOC.cshtml";
}
}
<div class="container">
    <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12 mt-20">
            <div class="modify-w-form contact post">
                <h3 style="text-align: center; color: #FF660F;">
                    @ViewBag.Title
                </h3>
                <p><h4 class="media-heading" style="text-align:center;font-size: 16px;">TẢI APP LIỀN TAY, BÁO NGAY VỀ MÁY</h4></p>
                @*<p class="text-center">
            <img src="https://stnhd.com/files/hientai/qrCode.png" />
        </p>*@
                <p style="text-align: center;">
                    <a href="https://tamtriluc.page.link/EwdR" target="_blank" rel="noopener" style="border-width:0px;border:0px;"><img src="https://stnhd.com/Files/hientai/AppStore.png" class="hs-image-widget " style="max-width: 45%; height: auto;" alt="PNG-26" title="PNG-26"></a>
                    &nbsp;
                    <a href="https://tamtriluc.page.link/EwdR" target="_blank" rel="noopener" style="border-width:0px;border:0px;"><img src="https://stnhd.com/Files/hientai/GooglePlay.png" class="hs-image-widget " style="max-width: 45%; height: auto;" alt="PNG-26" title="PNG-26"></a>
                </p>
            </div>
        </div>
    </div>
</div>

GCSOFT.MVC/GCSOFT.MVC.STNHD/Views/hientai/v.cshtml
@{
    ViewBag.Title = ViewBag.TitleVideo;
    Layout = "~/Views/Shared/_LayoutOC.cshtml";
}
<link href="@Url.Content("~/Content/Videos.css")" rel="stylesheet" />
<div class="container">
    @*<div class="jumbotron">
        <div class="txt divcenter">
            <h2>@ViewBag.TitleVideo</h2>
        </div>
    </div>*@
    <div class="row">
        <h3 style="text-align: center; font-weight: bold; color: #FF660F; font-family: Merriweather;">@ViewBag.TitleVideo</h3>
        <div class="col-xs-12 col-sm-5 col-md-5 col-lg-5">
            <div class="box-detail box-detail-lesson">
                <h3>Videos Hướng dẫn</h3>
                <div class="box-detail-inner">
                    <ul>
                        <li><a href="@Url.Action("v", "hientai", new { id = 10 })">Hướng dẫn cài đặt ứng dụng và đăng ký tài khoản Outlier</a></li>
                        <li><a href="@Url.Action("v", "hientai", new { id = 20 })">Hướng dẫn ghi nhận và theo dõi quá trình rèn luyện Hiền Tài</a></li>
                    </ul>
                </div>
            </div>
        </div>
        <div class="col-xs-12 col-sm-7 col-md-7 col-lg-7 mt-17">
            <div class="video" style="text-align:center">
                <video style="height: 600px" controls muted autoplay>
                    <source src="@ViewBag.link" type="video/mp4">
                    Your browser does not support the video tag.
                </video>
            </div>
        </div>
    </div>
</div>