GCSOFT.MVC/GCSOFT.MVC.AGENCY/Areas/HienTai/Controllers/BaoLuuController.cs
using AutoMapper;
using Dapper;
using GCSOFT.MVC.AGENCY.Areas.Administrator.Controllers;
using GCSOFT.MVC.AGENCY.Areas.Agency.Data;
using GCSOFT.MVC.AGENCY.Helper;
using GCSOFT.MVC.AGENCY.HienTaiService;
using GCSOFT.MVC.AGENCY.ViewModels.HienTai;
using GCSOFT.MVC.Data.Common;
using GCSOFT.MVC.Model.StoreProcedue;
using GCSOFT.MVC.Service.MasterDataService.Interface;
using GCSOFT.MVC.Service.SystemService.Interface;
using GCSOFT.MVC.Web.Helper;
using GCSOFT.MVC.Web.Helper.ActionFilters;
using PagedList;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Data.SqlClient;
using System.Linq;
using System.Reflection;
using System.Text;
using System.Web.Mvc;

namespace GCSOFT.MVC.AGENCY.Areas.HienTai.Controllers
{
    [CompressResponseAttribute]
    public class BaoLuuController : BaseController
    {
        #region -- Properties --
        private readonly IVuViecService _vuViecService;
        private readonly IOptionLineService _optionLineService;
        private readonly IMailSetupService _mailSetupService;
        private readonly ITemplateService _templateService;
        private string sysCategory = "HIENTAI_LOP";
        private bool? permission = false;
        private string hienTaiConnection = ConfigurationManager.ConnectionStrings["HienTaiConnection"].ConnectionString;
        #endregion

        ParentService parentService = new ParentService();
        StudentService studentService = new StudentService();
        ReserveService reserveService = new ReserveService();
        #region -- Contructor --
        public BaoLuuController
            (
                IVuViecService vuViecService,
                IOptionLineService optionLineService,
                IMailSetupService mailSetupService,
                ITemplateService templateService
            ) : base(vuViecService)
        {
            _vuViecService = vuViecService;
            _optionLineService = optionLineService;
            _mailSetupService = mailSetupService;
            _templateService = templateService;
        }
        #endregion
        public ActionResult Index(int? pageNumber)
        {
            #region -- Role user --
            permission = GetPermission(sysCategory, Authorities.View);
            if (!permission.HasValue) return RedirectToAction("Index", "Login", new { area = "administrator", url = CurrentUrl() });
            if (!permission.Value) return View("AccessDenied");
            #endregion

            int page = 0;
            int pageSize = 10;
            int.TryParse(pageNumber.ToString(), out page);
            if (page == 0) page = 1;
            ViewBag.StartSTT = 1;

            ViewBag.ListReserveCode = _optionLineService.FindAll("RESERVE");
            ViewBag.ListStudent = studentService.GetAllStudentDrop(GetUser().teacherInfo.AgencyId);
            ViewBag.ListApproveStatus = reserveService.GetApproveStatusDrop(GetUser().teacherInfo.AgencyId);

            List<O_Reserve> model = reserveService.GetAllReserve(string.Empty, string.Empty, 0, string.Empty, GetUser().teacherInfo.AgencyId);
            IPagedList<O_Reserve> data = model.ToPagedList(page, pageSize);
            return View(data);
        }

        [HttpPost]
        public ActionResult IndexContent(string code, string reserveCode, string studentId, string statusCode, int? pageNumber)
        {
            int pageSize = 10;
            int page = 0;
            int.TryParse(pageNumber.ToString(), out page);
            if (page == 0)
            {
                page = 1;
                ViewBag.StartSTT = 1;
            }
            else
            {
                ViewBag.StartSTT = ((page - 1) * pageSize) + 1;
            }

            ViewBag.code = code;
            ViewBag.reserveCode = reserveCode;
            ViewBag.studentId = studentId ?? "0";
            ViewBag.statusCode = statusCode;

            int studentIdConvert = 0;
            int.TryParse(studentId == null ? "0" : studentId, out studentIdConvert);

            List<O_Reserve> model = reserveService.GetAllReserve(code, reserveCode, studentIdConvert, statusCode, GetUser().teacherInfo.AgencyId);
            IPagedList<O_Reserve> data = model.ToPagedList(page, pageSize);
            return PartialView("_IndexContent", data);
        }
        
        public ActionResult Details(string code)
        {
            #region -- Role user --
            permission = GetPermission(sysCategory, Authorities.ViewDetail);
            if (!permission.HasValue) return RedirectToAction("Index", "Login", new { area = "administrator", url = CurrentUrl() });
            if (!permission.Value) return View("AccessDenied");
            #endregion
            return View(new ReserveService().GetBy(code, GetUser().teacherInfo.AgencyId));
        }
    }
}

GCSOFT.MVC/GCSOFT.MVC.AGENCY/Areas/HienTai/Views/BaoLuu/Details.cshtml
@model GCSOFT.MVC.AGENCY.ViewModels.HienTai.O_ReserveDetails
@{
    ViewBag.Title = "THÔNG TIN CHI TIẾT BẢO LƯU";
}
<div id="page_content_inner">
    <div class="md-card">
        <div class="md-card-toolbar">
            <h3 class="md-card-toolbar-heading-text">
                @ViewBag.Title
                @Html.HiddenFor(model => model.Code)
            </h3>
        </div>
        <div class="md-card-content gc-padding-top-8">
            <div class="uk-grid margin-top-0px">
                <div class="uk-width-medium-1-4">
                    <div class="uk-width-medium-1-1">
                        @Html.LabelFor(model => model.Code, htmlAttributes: new { @class = "uk-text-muted uk-text-small" })
                    </div>
                    <div class="uk-width-medium-1-1 margin-top-2px">
                        <span class="uk-text-middle">@Model.Code</span>
                    </div>
                    <hr class="gc-grid-divider uk-hidden-medium uk-hidden-large">
                </div>
                <div class="uk-width-medium-1-4">
                    <div class="uk-width-medium-1-1">
                        @Html.LabelFor(model => model.ReserveText, htmlAttributes: new { @class = "uk-text-muted uk-text-small" })
                    </div>
                    <div class="uk-width-medium-1-1 margin-top-2px">
                        <span class="uk-text-middle">@Model.ReserveText</span>
                    </div>
                    <hr class="gc-grid-divider uk-hidden-medium uk-hidden-large">
                </div>
                <div class="uk-width-medium-1-4">
                    <div class="uk-width-medium-1-1">
                        @Html.LabelFor(model => model.StudentName, htmlAttributes: new { @class = "uk-text-muted uk-text-small" })
                    </div>
                    <div class="uk-width-medium-1-1 margin-top-2px">
                        <span class="uk-text-middle">@Model.StudentName</span>
                    </div>
                    <hr class="gc-grid-divider uk-hidden-medium uk-hidden-large">
                </div>
                <div class="uk-width-medium-1-4">
                    <div class="uk-width-medium-1-1">
                        @Html.LabelFor(model => model.StatusName, htmlAttributes: new { @class = "uk-text-muted uk-text-small" })
                    </div>
                    <div class="uk-width-medium-1-1 margin-top-2px">
                        <span class="uk-text-middle">@Model.StatusName</span>
                    </div>
                    <hr class="gc-grid-divider uk-hidden-medium uk-hidden-large">
                </div>
            </div>
            <div class="uk-grid margin-top-0px">
                <div class="uk-width-medium-1-4">
                    <div class="uk-width-medium-1-1">
                        @Html.LabelFor(model => model.DateRequest, htmlAttributes: new { @class = "uk-text-muted uk-text-small" })
                    </div>
                    <div class="uk-width-medium-1-1 margin-top-2px">
                        <span class="uk-text-middle">@Model.DateRequest.ToString("dd/MM/yyyy")</span>
                    </div>
                    <hr class="gc-grid-divider uk-hidden-medium uk-hidden-large">
                </div>
                <div class="uk-width-medium-1-4">
                    <div class="uk-width-medium-1-1">
                        @Html.LabelFor(model => model.DateReserveStart, htmlAttributes: new { @class = "uk-text-muted uk-text-small" })
                    </div>
                    <div class="uk-width-medium-1-1 margin-top-2px">
                        <span class="uk-text-middle">@Model.DateReserveStart.ToString("dd/MM/yyyy")</span>
                    </div>
                    <hr class="gc-grid-divider uk-hidden-medium uk-hidden-large">
                </div>
                <div class="uk-width-medium-1-4">
                    <div class="uk-width-medium-1-1">
                        @Html.LabelFor(model => model.DateReserveEnd, htmlAttributes: new { @class = "uk-text-muted uk-text-small" })
                    </div>
                    <div class="uk-width-medium-1-1 margin-top-2px">
                        <span class="uk-text-middle">@Model.DateReserveEnd.ToString("dd/MM/yyyy")</span>
                    </div>
                    <hr class="gc-grid-divider uk-hidden-medium uk-hidden-large">
                </div>
                <div class="uk-width-medium-1-4">
                    <div class="uk-width-medium-1-1">
                        @Html.LabelFor(model => model.DateJourney, htmlAttributes: new { @class = "uk-text-muted uk-text-small" })
                    </div>
                    <div class="uk-width-medium-1-1 margin-top-2px">
                        <span class="uk-text-middle">@Model.DateJourney.ToString("dd/MM/yyyy")</span>
                    </div>
                    <hr class="gc-grid-divider uk-hidden-medium uk-hidden-large">
                </div>
            </div>
            <div class="uk-grid margin-top-0px">
                <div class="uk-width-medium-1-4">
                    <div class="uk-width-medium-1-1">
                        @Html.LabelFor(model => model.Content, htmlAttributes: new { @class = "uk-text-muted uk-text-small" })
                    </div>
                    <div class="uk-width-medium-1-1 margin-top-2px">
                        <span class="uk-text-middle">@Model.Content</span>
                    </div>
                    <hr class="gc-grid-divider uk-hidden-medium uk-hidden-large">
                </div>
                <div class="uk-width-medium-1-4">
                    <div class="uk-width-medium-1-1">
                        @Html.LabelFor(model => model.Answer, htmlAttributes: new { @class = "uk-text-muted uk-text-small" })
                    </div>
                    <div class="uk-width-medium-1-1 margin-top-2px">
                        <span class="uk-text-middle">@Model.Answer</span>
                    </div>
                    <hr class="gc-grid-divider uk-hidden-medium uk-hidden-large">
                </div>
            </div>
        </div>
    </div>
</div>

<footer id="footer" class="uk-text-center">
    <a id="btnReturn" href="@Url.Action("Index", "MaKichHoat", new { area = "HienTai" })" class="md-btn md-btn-danger md-btn-wave-light md-btn-icon">
        <i class="material-icons md-color-white">&#xE15E;</i>
        Quay Lại
    </a>
</footer>

GCSOFT.MVC/GCSOFT.MVC.AGENCY/Areas/HienTai/Views/BaoLuu/Index.cshtml
@using PagedList;
@model IPagedList<GCSOFT.MVC.AGENCY.ViewModels.HienTai.O_Reserve>
@{
    ViewBag.Title = "Danh Sách Bảo Lưu";
}
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
<style type="text/css">
    .pagination {
        display: inline-block;
        padding-left: 0;
        margin: 5px 0;
        border-radius: 4px;
    }
</style>
<div class="clearfix"></div>
<div class="container-fluid">
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="#">Trang chủ</a></li>
            <li class="breadcrumb-item active" aria-current="page">Bảo Lưu</li>
        </ol>
    </nav>
</div>
<div class="container-fluid">
    <div class="panel panel-default">
        <div class="panel-heading">TÌM KIẾM DỮ LIỆU</div>
        <div class="panel-body">
            @using (Ajax.BeginForm("IndexContent", "BaoLuu", new { area = "HienTai" },
                new AjaxOptions { HttpMethod = "POST", InsertionMode = InsertionMode.Replace, UpdateTargetId = "ReserveGrid" }, new { id = "frmReserve" }))
            {
                <div class="form-row">
                    <div class="form-group col-md-3">
                        <label>Mã Bảo Lưu</label>
                        <input type="text" class="form-control" name="Code" placeholder="Mã Bảo Lưu">
                    </div>
                    <div class="form-group col-md-3">
                        <label>Trạng Thái Bảo Lưu</label>
                        @Html.DropDownList("reserveCode", new SelectList(ViewBag.ListReserveCode, "Code", "Name"), "Tất cả", new { @id = "drdReserveCode", @class = "form-control", @placeholder = "Trạng Thái Bảo Lưu" })
                    </div>
                    <div class="form-group col-md-3">
                        <label for="inputEmail4">Học Viên Bảo Lưu</label>
                        @Html.DropDownList("studentId", new SelectList(ViewBag.ListStudent, "Id", "FullName"), "Tất cả", new { @id = "drdStudentId", @class = "form-control", @placeholder = "Học Viên Bảo Lưu" })
                    </div>
                    <div class="form-group col-md-3">
                        <label>Trạng Thái Duyệt Bảo Lưu</label>
                        @Html.DropDownList("statusCode", new SelectList(ViewBag.ListApproveStatus, "StatusCode", "StatusName"), "Tất cả", new { @id = "drdApproveStatus", @class = "form-control", @placeholder = "Trạng Thái Duyệt" })
                    </div>
                </div>
                <div class="form-row col-md-12 uk-text-right">
                    <a href="#" class="btn btn-success"><i class="material-icons md-color-white">playlist_add</i> Thêm mới</a>
                    <a href="#" class="btn btn-danger" onclick="SubmitFormByID('frmReserve');"><i class="material-icons md-color-white">&#xE8B6;</i> Tìm kiếm</a>
                </div>
            }
        </div>
    </div>
    <div id="ReserveGrid">
        @Html.Partial("_IndexContent", Model)
    </div>
</div>

@section scripts{
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
    <script src="/Areas/HienTai/Scripts/jquery.unobtrusive-ajax.min.js"></script>
    <script src="/Areas/HienTai/App/common.js"></script>
}

GCSOFT.MVC/GCSOFT.MVC.AGENCY/Areas/HienTai/Views/BaoLuu/_IndexContent.cshtml
@using PagedList.Mvc;
@using PagedList;
@model IPagedList<GCSOFT.MVC.AGENCY.ViewModels.HienTai.O_Reserve>
@{
    Layout = null;
    int StartStt = ViewBag.StartSTT;
}

<table class="table table-bordered">
    <thead>
        <tr>
            <th class="text-center">STT</th>
            <th class="text-center">Mã Bảo Lưu</th>
            <th class="text-center">Học Viên Bảo Lưu</th>
            <th class="text-center">Trạng Thái Bảo Lưu</th>
            <th class="text-center">Thời Gian Yêu Cầu</th>
            <th class="text-center">Thời Gian Bắt Đầu</th>
            <th class="text-center">Thời Gian Kết Thúc</th>
            <th class="text-center">Trạng Thái Duyệt</th>
            <th class="text-center">Thao tác</th>
        </tr>
    </thead>
    <tbody>
        @if (Model.Count > 0)
        {
            foreach (var item in Model)
            {
                <tr>
                    <td class="text-center">@StartStt</td>
                    <td class="text-center"><a href="@Url.Action("Details", "BaoLuu", new { area = "HienTai", code=item.Code })"><strong>@item.Code</strong></a></td>
                    <td>@item.StudentName</td>
                    <td>@item.ReserveText</td>
                    <td>@item.DateRequest.ToString("dd/MM/yyyy")</td>
                    <td>@item.DateReserveStart.ToString("dd/MM/yyyy")</td>
                    <td>@item.DateReserveEnd.ToString("dd/MM/yyyy")</td>
                    <td>@item.StatusName</td>
                    <td class="text-center">
                        <a href="#" class="btn btn-sm btn-icon btn-flat btn-default" title="Chỉnh Sửa">
                            <i class="material-icons md-24 uk-text-success">edit</i>
                        </a>
                        <button type="button" onclick='' class="btn btn-sm btn-icon btn-flat btn-default" title="Xóa">
                            <i class="material-icons md-24 uk-text-danger">&#xE872;</i>
                        </button>
                    </td>
                </tr>
                StartStt++;
            }
        }
        else
        {
            <tr>
                <td colspan="8">Dữ liệu không tồn tại.</td>
            </tr>
        }
    </tbody>
</table>
<div class="text-center">
    @if (Model.PageCount > 1)
    {
        @Html.PagedListPager(
            Model,
            pageNumber => Url.Action("IndexContent", "Bao Luu"
            , new { code = ViewBag.code, studentId = ViewBag.studentId, statusCode = ViewBag.statusCode, pageNumber }),
            PagedListRenderOptions.EnableUnobtrusiveAjaxReplacing(PagedListRenderOptions.PageNumbersOnly, new AjaxOptions() { HttpMethod = "POST", UpdateTargetId = "ReserveGrid" })
        )
    }
</div>