GCSOFT.MVC/GCSOFT.MVC.STNHD/Models/PageViewModels/AgencyViewModel.cs
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace GCSOFT.MVC.STNHD.Models.PageViewModels
{
    public class AgencyViewModel
    {
        public LoginResult UserInfo { get; set; }
        public IEnumerable<AgencyList> AgencyList { get; set; }
    }
}

GCSOFT.MVC/GCSOFT.MVC.STNHD/Controllers/StudentController.cs
//####################################################################
//# Copyright (C) 2021-2022, TTL JSC.  All Rights Reserved. 
//#
//# History:
//#     Date Time       Updater         Comment
//#     24/08/2021      Huỳnh Thử       Update
//####################################################################

using AutoMapper;
using GCSOFT.MVC.Data.Common;
using GCSOFT.MVC.Data.Repositories.MasterDataRepositories.Interface;
using GCSOFT.MVC.Model.MasterData;
using GCSOFT.MVC.Model.Transaction;
using GCSOFT.MVC.Service.MasterDataService.Interface;
using GCSOFT.MVC.Service.STNHDService.Interface;
using GCSOFT.MVC.Service.SystemService.Interface;
using GCSOFT.MVC.Service.Transaction.Interface;
using GCSOFT.MVC.STNHD.Helper;
using GCSOFT.MVC.STNHD.Models;
using Newtonsoft.Json;
using RestSharp;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Linq;
using System.Text;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;

namespace GCSOFT.MVC.STNHD.Controllers
{
    public class StudentController : BaseController
    {
        private readonly IShareInfoService _shareInfoService;
        private readonly IUserInfoService _userInfoService;
        private readonly IVuViecService _vuViecRepo;
        private readonly ISetupService _setupService;
        private readonly IClassService _classService;
        private readonly IStudentClassService _studentClassService;
        private readonly ITemplateService _templateService;
        private readonly ISMSService _smsService;
        private readonly IResetPasswordService _resetPassService;
        private readonly IMailSetupService _mailSetupService;
        private readonly ILoginEntryService _loginEntryService;
        private readonly ICardLineService _cardLineService;
        private string hasValue;
        private string API_URL = ConfigurationManager.AppSettings["apiBaseAddress"];
        private StringBuilder contentInfos;
        private M_LoginEntry loginEntry;
        public StudentController
            (
                IShareInfoService shareInfoService
                , IUserInfoService userInfoService
                , IVuViecService vuViecRepo
                , ISetupService setupService
                , IClassService classService
                , IStudentClassService studentClassService
                , ITemplateService templateService
                , ISMSService smsService
                , IResetPasswordService resetPassService
                , IMailSetupService mailSetupService
                , ILoginEntryService loginEntryService
                , ICardLineService cardLineService
            ) : base(shareInfoService)
        {
            _shareInfoService = shareInfoService;
            _userInfoService = userInfoService;
            _vuViecRepo = vuViecRepo;
            _setupService = setupService;
            _classService = classService;
            _studentClassService = studentClassService;
            _templateService = templateService;
            _smsService = smsService;
            _resetPassService = resetPassService;
            _mailSetupService = mailSetupService;
            _loginEntryService = loginEntryService;
            _cardLineService = cardLineService;
        }
        public ActionResult Index()
        {
            return Redirect("https://5phutthuocbai.com/download");
            if (GetUserInfo() != null)
            {
                FormsAuthentication.SignOut();
                CookieHelper.RemoveCookie("UserInfo", "LoginResult");
            }
            //ViewBag.ShareInfo = GetShareInfo();
            var userInfo = new UserInfoViewModel()
            {
                ClassList = Mapper.Map<IEnumerable<ClassList>>(_classService.FindAll(ClassType.Class, "SHOW")).ToList().ToSelectListItems(0)
            };
            ViewBag.returnUrl = Request.Params["ReturnUrl"];
            return View(userInfo);
        }
        // GET: Student
        public ActionResult registration()
        {
            //ViewBag.ShareInfo = GetShareInfo();
            return View();
        }
        [HttpPost]
        public ActionResult Create(UserInfoViewModel _userInfo)
        {
            var validCode = string.Empty;
            var hasUserName = !string.IsNullOrEmpty(_userInfoService.GetBy(_userInfo.userName).userName);
            if (hasUserName)
                validCode = "Tên Đăng Nhập đã tồn tại";
            if (!string.IsNullOrEmpty(validCode))
                return Json(new { s = "error", result = validCode }, JsonRequestBehavior.AllowGet);

            //var otpStatus = _smsService.CheckOTP(_userInfo.Phone, _userInfo.OTP);
            //var msg = "";
            //if (otpStatus.Equals("Nothing"))
            //    msg = "Mã OTP không tồn tại";
            //if (otpStatus.Equals("expired"))
            //    msg = "Mã OTP đã hết hạn";
            //if (!string.IsNullOrEmpty(msg))
            //    return Json(new { s = "error", result = msg }, JsonRequestBehavior.AllowGet);

            var userInfo = Mapper.Map<M_UserInfo>(_userInfo);
            userInfo.token = CryptorEngine.Encrypt(_userInfo.Email + "_0", true, "stnhdttl");
            userInfo.Phone2 = userInfo.Phone;
            userInfo.HasClass = true;
            userInfo.ActivePhone = false;
            hasValue = _userInfoService.Insert(userInfo);
            hasValue = _vuViecRepo.Commit();

            if (string.IsNullOrEmpty(hasValue))
            {
                var loginResult = Mapper.Map<LoginResult>(_userInfoService.CheckByUsername(_userInfo.userName, _userInfo.Password));
                FormsAuthentication.SetAuthCookie(loginResult.userName, true);
                loginResult.SessionId = System.Web.HttpContext.Current.Session.SessionID;
                CookieHelper.StoreInCookie("UserInfo", "", "LoginResult", Server.UrlEncode(JsonConvert.SerializeObject(loginResult)), null);
                SetDataLoginEntry(loginResult);
            }

            var status = string.IsNullOrEmpty(hasValue) ? "oke" : "error";
            return Json(new { s = status, result = status.Equals("oke") ? Url.Action("Index", "ClassInfo") : hasValue }, JsonRequestBehavior.AllowGet);
        }
        private void SetDataLoginEntry(LoginResult loginResult)
        {
            var loginEntryVM = new LoginEntryViewModel();
            var ipClient = GetIPAddress();
            //-- Get ip info
            if (!string.IsNullOrEmpty(ipClient))
            {
                var client = new RestClient(string.Format("http://api.ipstack.com/{0}?access_key=c2547274e399416b3c9e3f1afdf37fe9", ipClient));
                client.Timeout = -1;
                var request = new RestRequest(Method.GET);
                IRestResponse response = client.Execute(request);
                loginEntryVM = JsonConvert.DeserializeObject<LoginEntryViewModel>(response.Content);
            }

            //-- Get ip info +
            loginEntryVM.userName = loginResult.userName;
            loginEntryVM.SessionId = loginResult.SessionId;
            loginEntryVM.LoggedIn = true;
            loginEntryVM.DateLogin = DateTime.Now;
            loginEntry = Mapper.Map<M_LoginEntry>(loginEntryVM);
            hasValue = _loginEntryService.Insert(loginEntry);
            hasValue = _vuViecRepo.Commit();
        }
        /// <summary>
        /// Gửi OTP Cho Đăng Ký Thành Viên
        /// </summary>
        /// <param name="p">Phone No.</param>
        /// <param name="s">Seri Number</param>
        /// <returns></returns>
        public JsonResult SendOTPRegister(string p)
        {
            if (!_smsService.AllowSendSMS(p, 3))
                return Json(string.Format("Số điện thoại {0} đã được gửi {1} lần ngày hôm nay, vui lòng quay lại ngày hôm sau để tiếp tục", p, 3), JsonRequestBehavior.AllowGet);
            RandomNumberGenerator randomNumber = new RandomNumberGenerator();
            var otp = randomNumber.RandomNumber(1000, 9999);
            var smsTemplate = Mapper.Map<Template>(_templateService.Get("SMS_OTP"));
            var _content = StringUtil.StripTagsRegexCompiled(smsTemplate.Content.Replace("{{NAME}}", "5 Phut Thuoc Bai"));
            _content = _content.Replace("{{OTP}}", otp.ToString());
            _content = _content.Replace("{{HIEULUC}}", "hieu luc 5 phut");
            _content = _content.Replace("{{NOIDUNG}}", "xac thuc SDT dang ky tai khoan STNHD");
            var smsInfo = new SMSViewModel()
            {
                Type = SMSType.OTP,
                PhoneNo = p,
                OTP = otp.ToString(),
                Content = _content,
                DateInput = DateTime.Now.AddMinutes(5)
            };
            var smsHelper = new SMSHelper()
            {
                PhoneNo = smsInfo.PhoneNo,
                Content = smsInfo.Content
            };
            hasValue = smsHelper.Send();
            hasValue = _smsService.Insert(Mapper.Map<M_SMS>(smsInfo));
            hasValue = _vuViecRepo.Commit();
            return Json("", JsonRequestBehavior.AllowGet);
        }
        public ActionResult ResetPassword()
        {
            return View(new UserInfoViewModel());
        }
        public ActionResult ForgetUsername()
        {
            return View(new ResetPasswordViewModel());
        }
        [HttpPost]
        public ActionResult ResetPassword(UserInfoViewModel _userInfo)
        {
            var userInfo = Mapper.Map<UserInfoViewModel>(_userInfoService.CheckByUsernameAndEmail(_userInfo.userName, _userInfo.Email));
            if (string.IsNullOrEmpty(userInfo.userName))
                return Json(new { s = "error", result = "Tên Đăng Nhập và Email không trùng nhau" }, JsonRequestBehavior.AllowGet);
            var resetPassword = new ResetPasswordViewModel() { 
                Id = Guid.NewGuid(),
                Email = userInfo.Email,
                DocumentDate = DateTime.Now,
                ExpiryDate = DateTime.Now.AddMinutes(30),

GCSOFT.MVC/GCSOFT.MVC.STNHD/Controllers/SupportController.cs
using GCSOFT.MVC.Service.STNHDService.Interface;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace GCSOFT.MVC.STNHD.Controllers
{
    public class SupportController : BaseController
    {
        public SupportController
            (
                IShareInfoService shareInfoService
            ) : base(shareInfoService)
        {

        }
        public ActionResult Guide()
        {
            return View();
        }
        public ActionResult AgencyPolicy()
        {
            return View();
        }
        // GET: Support
        public ActionResult Student(int? id)
        {
            var _id = id ?? 12;
            switch (_id)
            {
                case 12:
                    ViewBag.TitleVideo = "Đăng nhập và kích hoạt tài khoản Siêu Trí Nhớ Học Đường";
                    ViewBag.link = "https://daotao.stnhd.com/Files/HuongDanDaiLy/12_HuongDan_STNHD_DKvaKichHoat_TK_STNHD.mp4";
                    break;
                case 13:
                    ViewBag.TitleVideo = "Hướng dẫn học viên đổi mật khẩu";
                    ViewBag.link = "https://daotao.stnhd.com/Files/HuongDanDaiLy/13_HuongDan_STNHD_CachDoiMatKhau_TK_STNHD.mp4";
                    break;
                case 14:
                    ViewBag.TitleVideo = "Hướng dẫn lấy lại tên đăng nhập";
                    ViewBag.link = "https://daotao.stnhd.com/Files/HuongDanDaiLy/14_HuongDan_STNHD_LayLaiTenDangNhap.mp4";
                    break;
                case 15:
                    ViewBag.TitleVideo = "Hướng dẫn lấy lại mật khẩu";
                    ViewBag.link = "https://daotao.stnhd.com/Files/HuongDanDaiLy/15_HuongDan_STNHD_LayLaiMatKhai_HocVien.mp4";
                    break;
               
            }
            return View();
        }
        public ActionResult Agency(int? id)
        {
            var _id = id ?? 1;
            switch (_id)
            {
                case 1:
                    ViewBag.TitleVideo = "Đại lý đăng nhập và đổi mật khẩu";
                    ViewBag.link = "https://daotao.stnhd.com/Files/HuongDanDaiLy/1_HuongDan_STNHD_DangNhapvaDoiMatKhau.mp4";
                    break;
                case 2:
                    ViewBag.TitleVideo = "Đại lý đặt đơn hàng thẻ cho Tâm Trí Lực";
                    ViewBag.link = "https://daotao.stnhd.com/Files/HuongDanDaiLy/2_HuongDan_STNHD_DatTheChoDaiLy.mp4";
                    break;
                case 3:
                    ViewBag.TitleVideo = "Đại lý nhận thẻ vào kho";
                    ViewBag.link = "https://daotao.stnhd.com/Files/HuongDanDaiLy/3_HuongDan_STNHD_NhanThe.mp4";
                    break;
                case 4:
                    ViewBag.TitleVideo = "Bán mã kích hoạt khách lẻ";
                    ViewBag.link = "https://daotao.stnhd.com/Files/HuongDanDaiLy/4_HuongDan_STNHD_BanMa.mp4";
                    break;
                case 5:
                    ViewBag.TitleVideo = "Bán mã kích hoạt khách lẻ số lượng lớn";
                    ViewBag.link = "https://daotao.stnhd.com/Files/HuongDanDaiLy/5_HuongDan_STNHD_XuatMa.mp4";
                    break;
                case 6:
                    ViewBag.TitleVideo = "Bán mã kích hoạt cho đại lý con";
                    ViewBag.link = "https://daotao.stnhd.com/Files/HuongDanDaiLy/6_HuongDan_STNHD_BanHangChoDaiLyCon.mp4";
                    break;
                case 7:
                    ViewBag.TitleVideo = "Bán mã kích hoạt cho cộng tác viên";
                    ViewBag.link = "https://daotao.stnhd.com/Files/HuongDanDaiLy/7_HuongDan_STNHD_BanHangChoCTV.mp4";
                    break;
                case 8:
                    ViewBag.TitleVideo = "Thu hồi thẻ đại lý con";
                    ViewBag.link = "https://daotao.stnhd.com/Files/HuongDanDaiLy/8_HuongDan_STNHD_ThuHoiThe.mp4";
                    break;
                case 9:
                    ViewBag.TitleVideo = "Thu hồi thẻ cộng tác viên";
                    ViewBag.link = "https://daotao.stnhd.com/Files/HuongDanDaiLy/9_HuongDan_STNHD_ThuHoiTheCTV.mp4";
                    break;
                case 10:
                    ViewBag.TitleVideo = "Thu hồi mã kích hoạt đã bán";
                    ViewBag.link = "https://daotao.stnhd.com/Files/HuongDanDaiLy/10_HuongDan_STNHD_ThuHoiMaKichHoatDaBan.mp4";
                    break;
                case 11:
                    ViewBag.TitleVideo = "Chỉnh sửa thông tin và gửi lại mật khẩu cho đại lý con, cộng tác viên";
                    ViewBag.link = "https://daotao.stnhd.com/Files/HuongDanDaiLy/11_HuongDan_STNHD_ChinhSuaThongTinvaGuiLaiMatKhauChoDaiLyCon.mp4";
                    break;
            }
            return View();
        }
    }
}

GCSOFT.MVC/GCSOFT.MVC.STNHD/Controllers/agencyController.cs
using AutoMapper;
using GCSOFT.MVC.Service.AgencyService.Interface;
using GCSOFT.MVC.Service.STNHDService.Interface;
using GCSOFT.MVC.STNHD.Models;
using GCSOFT.MVC.STNHD.Models.PageViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace GCSOFT.MVC.STNHD.Controllers
{
    public class agencyController : BaseController
    {
        private readonly IShareInfoService _shareInfoService;
        private readonly IAgencyService _agencyService;
        public agencyController
            (
                IShareInfoService shareInfoService
                , IAgencyService agencyService
            ) : base(shareInfoService)
        {
            _agencyService = agencyService;
            _shareInfoService = shareInfoService;
        }
        // GET: agency
        public ActionResult Index()
        {
            //ViewBag.ShareInfo = GetShareInfo();
            var agencyInfo = new AgencyViewModel();
            agencyInfo.UserInfo = GetUserInfo() ?? new LoginResult();
            agencyInfo.AgencyList = Mapper.Map<IEnumerable<AgencyList>>(_agencyService.FindAllHasImage()).OrderByDescending(d => d.ShowWebsite);
            return View(agencyInfo);
        }
    }
}

GCSOFT.MVC/GCSOFT.MVC.STNHD/Views/Support/Agency.cshtml
@{
    ViewBag.Title = "Hướng dẫn học viên";
}
<link href="@Url.Content("~/Content/Videos.css")" rel="stylesheet" />
<div class="container">
    <div class="jumbotron">
        <div class="txt divcenter">
            <h2>Hướng Dẫn Đối tác</h2>
        </div>
    </div>
    <div class="row">
        <div class="col-xs-12 col-sm-7 col-md-7 col-lg-7 mt-17">
            <div class="video">
                <h3>@ViewBag.TitleVideo</h3>
                <video width="100%" controls muted autoplay>
                    <source src="@ViewBag.link" type="video/mp4">
                    Your browser does not support the video tag.
                </video>
            </div>
        </div>

        <div class="col-xs-12 col-sm-5 col-md-5 col-lg-5">
            <div class="box-detail box-detail-lesson">
                <h3>Bài Học</h3>
                <div class="box-detail-inner">
                    <ul>
                        <li><a href="@Url.Action("Agency", "Support", new { id = 1 })">Đối tác đăng nhập và đổi mật khẩu</a></li>
                        <li><a href="@Url.Action("Agency", "Support", new { id = 2 })">Đối tác đặt đơn hàng thẻ cho Tâm Trí Lực</a></li>
                        <li><a href="@Url.Action("Agency", "Support", new { id = 3 })">Đối tác nhận thẻ vào kho</a></li>
                        <li><a href="@Url.Action("Agency", "Support", new { id = 4 })">Bán mã kích hoạt khách lẻ</a></li>
                        <li><a href="@Url.Action("Agency", "Support", new { id = 5 })">Bán mã kích hoạt khách lẻ số lượng lớn</a></li>
                        <li><a href="@Url.Action("Agency", "Support", new { id = 6 })">Bán mã kích hoạt cho Đối tác con</a></li>
                        <li><a href="@Url.Action("Agency", "Support", new { id = 7 })">Bán mã kích hoạt cho cộng tác viên</a></li>
                        <li><a href="@Url.Action("Agency", "Support", new { id = 8 })">Thu hồi thẻ Đối tác con</a></li>
                        <li><a href="@Url.Action("Agency", "Support", new { id = 9 })">Thu hồi thẻ cộng tác viên</a></li>
                        <li><a href="@Url.Action("Agency", "Support", new { id = 10 })">Thu hồi mã kích hoạt đã bán</a></li>
                        <li><a href="@Url.Action("Agency", "Support", new { id = 11 })">Chỉnh sửa thông tin và gửi lại mật khẩu cho Đối tác con, cộng tác viên</a></li>
                    </ul>
                </div>
            </div>
        </div>

    </div>
</div>

GCSOFT.MVC/GCSOFT.MVC.STNHD/Views/Support/AgencyPolicy.cshtml
@model GCSOFT.MVC.STNHD.Models.PageViewModels.SocialViewModel
@using GCSOFT.MVC.Model.MasterData
@{
    ViewBag.Title = "Chính Sách Đối Tác - Siêu Trí Nhớ Học Đường";
}
<div class="container">
    <div class="jumbotron">
        <div class="txt">
            <h2>Chính Sách Đối Tác</h2>
        </div>
        <p class="jumbotron-img"><img src="@Url.Content("~/Content/images/banner-detail.png")" alt=""></p>
    </div>
    <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
            <div class="ask-answer">
                <div class="post">
                    <div class="post-top">
                        <h4>Chính sách đối tác tháng 6/2021</h4>
                        <p class="txt">Tổng hợp chính sách đối tác/cộng tác viên Siêu Trí Nhớ Học Đường tháng 06/2021</p>
                        <div class="text-left post-btn"><a href="https://sieutrinhohocduong.com/Files/AgencyPolicy/ChinhSachDaiLyT6.pdf" target="_blank">Xem chi tiết</a></div>
                    </div>
                    <div class="clear-both"></div>
                </div>
                <div class="clear-both"></div>
            </div>
        </div>
    </div>
</div>

GCSOFT.MVC/GCSOFT.MVC.STNHD/Views/Support/Guide.cshtml
@{
    ViewBag.Title = "Hướng dẫn học Siêu Trí Nhớ Học Đường";
}
<link href="@Url.Content("~/Content/Videos.css")" rel="stylesheet" />
<div class="container">
    <div class="jumbotron">
        <div class="txt divcenter">
            <h2>Hướng Dẫn Học Siêu Trí Nhớ Học Đường</h2>
        </div>
    </div>
    <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12 mt-17">
            <div class="video">
                <h3>@ViewBag.TitleVideo</h3>
                <video width="100%" controls muted autoplay>
                    <source src="https://sieutrinhohocduong.com/Files/HocVien/HuongDan_STNHD_ver03.mp4" type="video/mp4">
                    Your browser does not support the video tag.
                </video>
            </div>
        </div>
    </div>
</div>

GCSOFT.MVC/GCSOFT.MVC.STNHD/Views/Support/Student.cshtml
@{
    ViewBag.Title = "Hướng dẫn học viên";
}
<link href="@Url.Content("~/Content/Videos.css")" rel="stylesheet" />
<div class="container">
    <div class="jumbotron">
        <div class="txt divcenter">
            <h2>Hướng Dẫn Học Viên</h2>
        </div>
    </div>
    <div class="row">
        <div class="col-xs-12 col-sm-7 col-md-7 col-lg-7 mt-17">
            <div class="video">
                <h3>@ViewBag.TitleVideo</h3>
                <video width="100%" controls muted autoplay>
                    <source src="@ViewBag.link" type="video/mp4">
                    Your browser does not support the video tag.
                </video>
            </div>
        </div>

        <div class="col-xs-12 col-sm-5 col-md-5 col-lg-5">
            <div class="box-detail box-detail-lesson">
                <h3>Bài Học</h3>
                <div class="box-detail-inner">
                    <ul>
                        <li><a href="@Url.Action("Student", "Support", new { id = 12 })">Đăng nhập và kích hoạt tài khoản Siêu Trí Nhớ Học Đường</a></li>
                        <li><a href="@Url.Action("Student", "Support", new { id = 13 })">Hướng dẫn học viên đổi mật khẩu</a></li>
                        <li><a href="@Url.Action("Student", "Support", new { id = 14 })">Hướng dẫn lấy lại tên đăng nhập</a></li>
                        <li><a href="@Url.Action("Student", "Support", new { id = 15 })">Hướng dẫn lấy lại mật khẩu</a></li>
                    </ul>
                </div>
            </div>
        </div>

    </div>
</div>